name: CI
on: [push]
jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      name: 启动jdk11
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: 编译
      run: mvn clean package -DskipTest=true
    - name: 查看文件
      run: ls ${{ github.workspace }}
        
